### ISSUE TITLE
Random API issues

### ISSUE THREAD

**Issue by TomNUSDS** [drobadey/test-project#1]
I'm going to reuse this issue for minor API issues I encounter while trying playing with converting it to a working code.

I will update this issue with items that can be checked off as they are addressed/fixed. If any items are big enough or need to be moved to a separate issue for group discussion, that's fine.

- [x] `ClientSummaryQuery` (v1.0b8)
  `NameSummary` has nested fields (`FirstName`, `LastName`, `NameSuffix`). For whatever reason, nested schemas have issues when using `fastapi-codegen`. Maybe remove the NameSummary and just put these three fields at the root along side `DateOfBirth`, `SocialSecurityNumber`
  
  This is the generate code issue:
```python
class ClientSummaryQuery(BaseModel):
    NameSummary: Optional[NameSummary] = None
    DateOfBirth: Optional[date] = Field(
        None,
        description='Optional date of birth of client. A date in ISO 8601 format. The year is always required, the month + day is optional.',
    )
    SocialSecurityNumber: Optional[constr(pattern=r'^[0-9]{4}$')] = Field(
        None,
        description='Social Security Number, should be formatted as 4 characters representing the last 4 digit',
    )
```
`NameSummary: Optional[NameSummary]` <- `NameSummary` for the field and Type

- [x] `ClientSummaryQuery` (v1.0b8)
  Seems to be missing pagination parameters `offset` and `limit` when code is generated.

- [x] `ClientSummary` (v1.0b8)
```yaml
    ClientSummary:
      allOf: 
        -  $ref: '#/components/schemas/ClientSummaryQuery'
```
  The above suggestions of including `offset` and `limit` means these now end up in the Summary result. Probably better to just copy/paste the fields expected to be returned.
  
  
  - [ ] `ClientSummaryQuery` (v1.0b8) partial DateOfBirth matching
  This ends up being hard because of a few things:
    - The built-in validator rejects the query if it isn't a valid date.
    - The database schema contains a date object, so `date_part('year', mydate) == year` is needed OR some clever cast to a string.

  - [ ] #3
```yaml
class ClientBase(BaseModel):
    Name: Optional[Name] = None
    SSN: Optional[SSN] = None
    VitalStatistics: Optional[VitalStatistics] = None
    RaceAndEthnicity: Optional[RaceAndEthnicity] = None
    Gender: Optional[Gender] = None
    Veteran: Optional[Veteran] = None
    # UserId: Optional[constr(max_length=32)] = None
```

  - [x] `ClientBase` (v1.0b8) field names match type and generate python errors. e.g.
```yaml
class ClientBase(BaseModel):
    name: Optional[Name] = None # Name -> name
    ssn: Optional[SSN] = None # SSN -> ssn
    vitalStatistics: Optional[VitalStatistics] = None
    raceAndEthnicity: Optional[RaceAndEthnicity] = None
    gender: Optional[Gender] = None
    veteran: Optional[Veteran] = None
    # UserId: Optional[constr(max_length=32)] = None # should come from JWT
```

  - [ ] `ClientBase` (v1.0b8) for create, some fields are likely always required?
 `vitalStatistics.dateOfBirth`, `name.lastName`, `ssn.socialSecurityNumber`

  - [x] `ClientBase` (v1.0b8) Pattern for SocialSecurityNumber is wrong.
    It is currently `"^[0-9xX]{9}$"`  which is for masked social security numbers (`xX`) it should be `"^[0-9]{9}$"` ... also, this format means 123456789 and the `-` **cannot** be provided. If you want to _require_ dashes then `"^[0-9]{3}-[0-9]{2}-[0-9]{4}$"`
    Related note: how is it stored in the database? It need to be converted in the python code if the API formatting doesn't match how the database stores it.
    
  - [x] ALL responses. (v1.0b8)
  ```json
{
  "query": {
    "limit": 25,
    "offset": 0
  },
  "result": [
    // resources for first "page".
  ],
  "total": 34
}
```

The way the validator in python works, the response needs to be correct based on the api endpoints. So there's probably a need for a `BaseResponse` that includes the `query` and `total`, but _not_ the `result`, then you'd mix in the `result[]` that's specific for type the endpoint uses.
